src/components/home/CommunityList.tsx, src/components/home/Policy.tsx, src/components/shared/Title.tsx
변경 사항을 체크해주세요.
- 미사용 주석 배포시 오류 발생하여 삭제 처리
=> fix: 미사용 import 삭제

src/components/shared/ListItem.tsx
변경 사항을 체크해주세요.
- src/components/shared/ListItem.tsx
- list 컴포넌트 작성자 css 수정
=> fix : list 컴포넌트 작성자 css 수정

src/components/shared/TopButton.tsx, src/components/style/topBtn.ts, src/layouts/MainLayout.tsx
#2 
변경 사항을 체크해주세요.
- src/components/shared/TopButton.tsx
- top 버튼 구현
=> feat: top-btn 컴포넌트 구현

index.html, src/components/shared/TopButton.tsx, src/components/shared/WriteButton.tsx, src/components/style/fixedCircleBtn.ts, src/pages/Home/Home.tsx
#2 
변경 사항을 체크해주세요.
- index.html
- src/components/shared/TopButton.tsx
- src/components/shared/WriteButton.tsx
- src/components/style/fixedCircleBtn.ts
- 
- 글작성 버튼 컴포넌트 구현
- index.html 헤드 title 변경
=> feat : write 버튼 구현

src/api/comment/delete.ts, src/api/comment/list.ts, src/api/comment/modify.ts, src/api/comment/register.ts, src/api/common/category.ts, src/api/community/content.ts, src/api/community/delete.ts, src/api/community/list.ts, src/api/community/register.ts, src/pages/MyPage/MyPage.tsx
src/pages/MyPage/MyPage.tsx
마이페이지 기본 구현
API 연결
백 연결
프로필 수정 페이지 생성
페이지 이동 라우터 추가
=> feat: 마이페이지 기본 구현

src/features/Policy/api.ts, src/features/Policy/store.ts, src/features/Policy/types.ts, src/pages/Policy/Policy.tsx, src/pages/Policy/PolicyList.tsx
#5 
confilcts: public/data/contests-list.json
feat:
src/features/Policy/api.ts
src/features/Policy/store.ts
src/features/Policy/types.ts
src/pages/Policy/Policy.tsx
src/pages/Policy/PolicyList.tsx
1. 무한 confilcts 해결
2. 청년정책 페이지 데이터 fetching 확인
1. 청년정책 페이지 퍼블리싱
2. 청년정책 페이지 검색, 필터 적용
3. 청년정책 페이지 페이지네이션
=> feat: 청년정책 페이지 데이터 fetch 기능 구현

src/api/contest/list.ts, src/components/shared/Card.tsx, src/pages/Contest/ContestList.tsx, src/routers/AppRouter.tsx
변경 사항을 체크해주세요.
- public/data/contests-list.json
- src/api/contest/list.ts
- src/pages/Contest/ContestList.tsx
- src/routers/AppRouter.tsx
=> fix : 공모전 리스트 수정

src/api/community/list.ts, src/pages/Community/CommunityList.tsx
#35 
변경 사항을 체크해주세요.
- src/api/community/list.ts  
- src/pages/Community/CommunityList.tsx
- 커뮤니티 리스트 데이터 타입 오류 수정
=> fix: 커뮤니티 리스트 data type 오류 수정

src/pages/Community/CommunityList.tsx
변경 사항을 체크해주세요.
- src/pages/Community/CommunityList.tsx
- 공통컴포넌트 props 값 수정으로 인한 오류 수정
=> fix:공통 컴포넌트 변경에 따른 오류 수정

src/App.css, src/components/shared/Fillter.tsx, src/components/style/input.ts, src/pages/Contest/ContestList.tsx
#39 
변경 사항을 체크해주세요.
- src/App.css
- src/components/shared/Fillter.tsx
- src/pages/Contest/ContestList.tsx
- 리셋 버튼 기능 추가
- css 수정
=> fix : 필터 초기화 버튼

src/api/community/list.ts
변경 사항을 체크해주세요.
- src/api/community/list.ts
- 
- 커뮤니티 리스트 param 명 변경
=> feat: 커뮤니티 리스트 param 명 변경

src/components/home/PopularContestCard.tsx, src/components/shared/Header.tsx, src/components/style/header.ts, src/main.tsx
#46 #47  #48 
- src/components/home/PopularContestCard.tsx
- src/components/shared/Header.tsx
- src/components/style/header.ts
- src/main.tsx
- 모바일 메뉴 누르면 메뉴 닫히기
- 모바일 상태에서 다크모드 전환 버튼 추가
- 메인페이지 인기공모전 컴포넌트 모바일 CSS 수장
=> fix : 메인페이지 모바일 대응 수정 

src/components/shared/Fillter.tsx
#60 
변경 사항을 체크해주세요.
- src/components/shared/Fillter.tsx
- 고정 레이아웃 구현
=> style : filter add 될때 생기는 높이 증가 현상 고정 레이아웃 구현

src/components/home/MainBanner.tsx, src/constants/ImageSrc.ts
#50 
변경 사항을 체크해주세요.
- src/components/home/MainBanner.tsx
- 메인슬라이드 img src 경로 수정
=> fix : 메인슬라이드 img src 경로 수정

src/components/shared/Fillter.tsx, src/features/Policy/FilterGroupSection.tsx.tsx, src/features/Policy/TreeFilterGroupSection.tsx, src/pages/Policy/Policy.tsx, src/pages/Policy/PolicyList.tsx
#5 
변경 사항을 체크해주세요.
- **/components/shared/Fillter.tsx**
- /features/Policy/*
- /pages/Policy/*
- husky 룰에 의한 lint 에러 해결 (배포 이슈)
- 디버깅용 console.log 삭제 (lint warning)
- filter 자식 노드 선택 및 필터링 처리
- 리스트 없는 경우 img 보여주기
=> fix: filter 자식 요소 관련 수정 사항 및 lint 에러 해결

src/components/home/PolicySider.tsx
#25 
변경 사항을 체크해주세요.
- src/components/home/PolicySider.tsx
- 정책 list 링크 기능 반영
=> feat : 정책 list 링크 구현

src/features/Policy/TreeFilterGroupSection.tsx, src/features/Policy/api.ts, src/features/Policy/filterGroups.ts, src/pages/Policy/Policy.tsx
#5 
변경 사항을 체크해주세요.
- /pages/Policy/Policy.tsx
- 검색 기능 추가
=> feat: 청년 정책 검색, 페이지네이션 기능 추가

src/api/contest/list.ts, src/components/contest/DetailContent.tsx, src/components/contest/DetailInfo.tsx, src/pages/Stats/Stats.tsx, src/routers/AppRouter.tsx
#72 
변경 사항을 체크해주세요.
- src/api/contest/list.ts
- src/components/contest/DetailContent.tsx
- 프론트 공모전 bookmark  api 추가
=> feat : 공모전 bookmark 기능 구현

src/api/community/content.ts, src/api/community/list.ts, src/api/contest/listByCategory.ts, src/api/scrap/toggle.ts, src/components/shared/ListItem.tsx, src/pages/Community/CommunityContent.tsx, src/pages/Community/CommunityList.tsx, src/pages/Community/CommunityWrite.tsx
변경 사항을 체크해주세요.
- 커뮤니티 & 스크랩 & 공모전
- 커뮤니티 디자인 수정 & 로그인별 기능 제한
- 스크랩 기능 추가
- 로그인 성공 후 테스트 필요 
-
=> feat: 커뮤니티 디자인 수정 & 로그인별 기능 제한 & 스크랩 기능 추가

src/api/contest/list.ts, src/components/contest/DetailInfo.tsx, src/features/contest/useBookmark.ts, src/features/contest/useGetList.ts, src/types/contestType.ts
#72
변경 사항을 체크해주세요.
- src/api/contest/list.ts
- src/features/contest/useBookmark.ts
- src/types/contestType.ts
- 북마크 cnt 조회 
- 북마크 여부
- tanstack query 적용
=> feat : 북마크 cnt 조회 및 tanstack query 적용

src/components/contest/DetailInfo.tsx, src/features/contest/useBookmark.ts
#76 
변경 사항을 체크해주세요.
- src/features/contest/useBookmark.ts
- 북마크 tanstack query 낙관적 업데이트 추가
=> feat : 북마크 tanstack query 낙관적 업데이트 추가

src/components/home/MainBanner.tsx, src/index.css
#50 
변경 사항을 체크해주세요.
- src/components/home/MainBanner.tsx
- src/index.css
- 메인 배너 text color 수정
=> style : 메인 배너 text color 수정

src/api/contest/list.ts, src/components/contest/DetailInfo.tsx, src/components/shared/Header.tsx, src/features/contest/useBookmark.ts, src/pages/Contest/ContestDetail.tsx
#72 
변경 사항을 체크해주세요.
- src/api/contest/list.ts
- src/features/contest/useBookmark.ts
- api 분리
=> fix : 북마크 API 분리

src/components/shared/Card.tsx, src/pages/Contest/ContestForm.tsx, src/store/ContestFormStore.ts, src/types/contestType.ts, yarn.lock
#83 
변경 사항을 체크해주세요.
- src/components/shared/Card.tsx
-  src/pages/Contest/ContestForm.tsx
- src/store/ContestFormStore.ts
- contest-detail 오류 수정
- 카테고리 타입 변경으로 인해 터진것으로 판단
- 이후 상세페이지 확인했는데 전반적으로 로직 수정이 필요한 상황
- 우선 주석처리 해놓고 이후 재구현 들어갈 예정
=> fix : contest-detail 부분 오류

src/components/contest/ContestFormTemplate.tsx, src/components/contest/DetailInfo.tsx, src/components/shared/Card.tsx, src/components/shared/FileInput.tsx, src/pages/Contest/ContestDetail.tsx, src/pages/Contest/ContestList.tsx, src/pages/Contest/ContestUpdate.tsx, src/types/contestType.ts, src/utils/bufferJsonToBlob.ts
#97 
변경 사항을 체크해주세요.
- src/components/contest/ContestFormTemplate.tsx
- src/components/shared/Card.tsx
- src/components/shared/FileInput.tsx
- src/pages/Contest/ContestDetail.tsx
- src/pages/Contest/ContestList.tsx
- src/pages/Contest/ContestUpdate.tsx
- src/types/contestType.ts
- src/utils/bufferJsonToBlob.ts
-  contest list get image
- 수정페이지 이미지 기능
=> feat : contest  image

src/components/community/content/Header.tsx
변경 사항을 체크해주세요.
- 미사용 import 정리
=> fix: 미사용 import 정리

src/api/contest/contestApi.ts, src/components/community/list/EmptyState.tsx, src/components/contest/ContestFormTemplate.tsx, src/pages/Community/CommunityWrite.tsx, src/pages/Contest/ContestUpdate.tsx, src/routers/AppRouter.tsx, src/types/communityWriteType.ts
#98 
변경 사항을 체크해주세요.
- [ㅌ] 버그 수정
- src/api/contest/contestApi.ts
- src/components/contest/ContestFormTemplate.tsx
- src/pages/Community/CommunityWrite.tsx
- src/pages/Contest/ContestUpdate.tsx
- 이미지 변경 안할시 image api 호출 X
=> fix : 이미지 변경 안할시 image api 호출 X

src/pages/Community/CommunityWrite.tsx, src/types/communityWriteType.ts
=> fix: 병합본 수정

src/components/shared/ListItem.tsx, src/pages/Community/CommunityWrite.tsx, src/pages/MyPage/CompanyMypage.tsx, src/pages/MyPage/PersonalMypage.tsx, src/types/communityWriteType.ts
변경 사항을 체크해주세요.
src/components/shared/ListItem.tsx
src/pages/MyPage/CompanyMypage.tsx
src/pages/MyPage/PersonalMypage.tsx
리스트아이템 수정하여 마이페이지 내 공모전 태그 DB버전,크롤링버전 모두 대응하도록 변경
=> fix : 공모전 크롤링 데이터 리스트 내 태그 표시 수정

src/components/shared/ListItem.tsx
src/components/shared/ListItem.tsx
프론트 배포 오류 문제 수정(ListItem 코드 일부 복원)
=> fix : 프론트 배포 오류 문제 수정(ListItem 코드 일부 복원)

src/components/style/footer.ts, src/layouts/MainLayout.tsx
#20 
변경 사항을 체크해주세요.
- src/components/style/footer.ts
- src/layouts/MainLayout.tsx
-  footer 위치 조정
=> style : footer 위치 조정

src/layouts/MainLayout.tsx
#107 
변경 사항을 체크해주세요.
- src/layouts/MainLayout.tsx
- main content 넓이 문제
=> fix : main content 넓이 문제

src/pages/Contest/ContestDetail.tsx
변경 사항을 체크해주세요.
- src/pages/Contest/ContestDetail.tsx
- 공모전 커뮤니티 연결 link 수정
=> fix : 공모전 커뮤니티 불러오기 수정

src/pages/MyPage/CompanyMypage.tsx, src/pages/MyPage/PersonalMypage.tsx
=> fix : 프론트배포 오류 페이지 수정

src/components/contest/ContestFormTemplate.tsx
변경 사항을 체크해주세요.
- src/components/contest/ContestFormTemplate.tsx
- 폼 취소 추가
=> fix : 공모전 폼 취소 수정
